#:schema node_modules/wrangler/config-schema.json
name = "hr-website"
compatibility_date = "2024-04-03"

[vars]

[[kv_namespaces]]
binding = "VISIT_KV"
id = "aae7ae232db5401fbea3b01adaddf832"
preview_id = "aae7ae232db5401fbea3b01adaddf832"
